### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by maddin200** [erich666/GraphicsGems#17]
GraphicsGems-master\gemsiv\interp_fast.c line 71
do statement after return cannot reached

**Comment by erich666** [comment]
This is some of the funkiest code I've ever seen: a switch statement whose cases toss you into the middle of do/while loops. It's like a puzzle.

However, this code _is_ reachable. Say the case statement executed is pos4. It will execute the statements that follow, then hit the while(), then (sometimes) return to the top of the do/while and execute line 71 on down. So, the statement is reachable.
