### ISSUE TITLE
Find a bug in gemsiv/clahe.c

### ISSUE THREAD

**Issue by liandaoacc** [erich666/GraphicsGems#19]
In gemsiv/clahe.c, **lin 226**, `pImage = &pImagePointer[uiSizeX];` should be `pImage = &pImagePointer[-uiSizeX];`. At the original version, it is `pImage = &pImagePointer[-uiSizeX];`.

**Comment by erich666** [comment]
Thanks very much, and it's now fixed. The commit [here](https://github.com/erich666/GraphicsGems/commit/240e90613c85693fe988f18d2546c7f95d0e257a) introduced this problem a year ago, and it slipped by me in review among the endless casting changes. I've gone over the submission again and believe no other bugs were introduced.

**Comment by gonsolo** [comment]
There was a problem before my commit: Unary minus of an unsigned int gives an unsigned int which probably not what you want here. I have the correct fix in my repository. Please pull.
https://github.com/gonsolo/GraphicsGems/commit/5eff48b8d9f66c3ec0d23e4690a746ca63798679

**Comment by erich666** [comment]
Thanks, and fixed (no idea how to make a pull request from your branch; I thought you'd submit a PR for me to accept).
