### ISSUE TITLE
name mismatch

### ISSUE THREAD

**Issue by maddin200** [erich666/GraphicsGems#21]
gems\AAPolyScan.c line 64
Declaration:
void renderScanline(Vertex* left, Vertex* right, int y, Surface* object);

Definition:
void renderScanline(Vl, Vr, y, object)
	Vertex *Vl, *Vr; 	/* polygon vertices interpolated */
					/* at scanline */   
	int y;			/* scanline coordinate */
	Surface *object;	/* shading parms for this object */

**Comment by erich666** [comment]
Fixed. Out of interest, @maddin200, does this actually matter to any compiler (i.e., the code won't compile), or is this just a warning?

**Comment by maddin200** [comment]
The issue is only of style type. Only in cases like:
int myfunc(int a, int b); // interface

int myfunc(int b, int a)
{
....

it is more serious (will also compile)
