### ISSUE TITLE
Criteria to decide whether to try to re-parameterize in FitCurves is bad (scale-dependent)

### ISSUE THREAD

**Issue by jimmyland** [erich666/GraphicsGems#23]
e.g. if units are such that user's `error` threshold is less than 1, the function will never try to re-parameterize.  Based on the usage example (where error is 4.0), I think the intent would be preserved if you just set `iterationError = error * 4.0;`

bad code is here:
https://github.com/erich666/GraphicsGems/blob/4d1d0a0e4f27f72e2930d369fa7132a253468bcf/gems/FitCurves.c#L113
(and iterationError is used at line 146)

**Comment by erich666** [comment]
Thanks. I've attempted to contact the author, Phil Schneider, for his opinion.

**Comment by jimmyland** [comment]
Alternatively I could do a PR that exposes the error scale factor as a parameter?  (and that line would then become `iterationError = error * iterationErrorScaleFactor;`?)

**Comment by erich666** [comment]
The good news is that Philip Schneider recently responded, so I'm hoping he'll look at the code soon and figure out what's the most sensible.

**Comment by erich666** [comment]
Pinged Philip.

**Comment by erich666** [comment]
Philip replied: "The suggested change is probably OK." So I've checked it in, and pointed the interested user at this issue for more details.
