### ISSUE TITLE
How to fit a cubic spline curve to a set of digitized points ?

### ISSUE THREAD

**Issue by 914805218** [erich666/GraphicsGems#29]
thanks a lot

**Comment by LysanderGG** [comment]
I don't think this is the place for questions like this.
You could find answers in the following links:

https://stackoverflow.com/questions/6299019/how-can-i-fit-a-b%C3%A9zier-curve-to-a-set-of-data

https://pomax.github.io/bezierinfo/#curvefitting

**Comment by 914805218** [comment]
thanks a lot
but the links is the answer of [fit a bezier curve to a set of digitized points]
i want fit a cubic spline curve, not a bezier curve
