### ISSUE TITLE
gemsiii comp issue

### ISSUE THREAD

**Issue by nyotis** [erich666/GraphicsGems#4]
erased #include <malloc.h> in GraphicsGems/gemsiii/contour.c and GraphicsGems/gemsiii/filter.c 
I get 
bsp.c:337:34: error: passing 'double *' to parameter of incompatible type 'double'; dereference with *PointAtDistance(ray, distance, &p);

_gcc version 4.8.2 (MacPorts gcc48 4.8.2_0)_

**Comment by erich666** [comment]
I think this one is now fixed (a mere two years later I realized I should close this issue if so) - give it a look if you wish and let me know if the latest code is working for you.

**Comment by erich666** [comment]
Closing for lack of response.
